repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l, '99']
        language_version: python3.10
        verbose: true
        exclude: .*auvsi_suas.*
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy
        exclude: .*auvsi_suas.*
        verbose: true
        args: ["--ignore-missing-imports", "--show-error-codes"]