repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l, '99']
        language_version: python3.10
        verbose: true
        exclude: ^server/auvsi_suas.*
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy
        exclude: ^(server/auvsi_suas.*|server/utils/(params|decorators).py)$
        verbose: true
        args: ["--ignore-missing-imports", "--show-error-codes", "--follow-imports", "skip"]

ci:
  autofix_prs: false