name: Black

on: [push, pull_request]

jobs:
  black:
    name: Check Python Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "-l 99 --extend-exclude auvsi_suas --check --diff --color"
